### ISSUE TITLE
grab_legend() not found 

### ISSUE THREAD

**Issue by reika2** [phenological/mva-plots#12]
The following error came up running plotScores()
Error in grab_legend(test) : could not find function "grab_legend"

**Comment by 75000089** [comment]
Grr it does this sometimes. And at random. I’ll try running a test on my end but otherwise I’ll come take a look. You’ve got the latest version right?

From: reika2 ***@***.***>
Date: Tuesday, 4 July 2023 at 4:21 pm
To: phenological/mva-plots ***@***.***>
Cc: Lucy Grigoroff ***@***.***>, Assign ***@***.***>
Subject: [phenological/mva-plots] grab_legend() not found (Issue #12)
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

The following error came up running plotScores()
Error in grab_legend(test) : could not find function "grab_legend"

**Comment by reika2** [comment]
Fixed Thank you!
